  export const currencyList =
   [   {currecyCode:"AED",currencyName: "United Arab Emirates Dirham"},
       {currecyCode:"AFN",currencyName: "Afghan Afghani"},
       {currecyCode:"ALL",currencyName: "Albanian Lek"},
       {currecyCode:"AMD",currencyName:"Armenian Dram"},
       {currecyCode:"ANG",currencyName: "Netherlands Antillean Guilder"},
       {currecyCode:"AOA",currencyName: "Angolan Kwanza"},
       {currecyCode:"ARS",currencyName: "Argentine Peso"},
       {currecyCode:"AUD",currencyName: "Australian Dollar"},
       {currecyCode:"AWG",currencyName: "Aruban Florin"},
       {currecyCode:"AZN",currencyName: "Azerbaijani Manat"},
       {currecyCode:"BAM",currencyName: "Bosnia-Herzegovina Convertible Mark"},
       {currecyCode:"BBD",currencyName: "Barbadian Dollar"},
       {currecyCode:"BDT",currencyName: "Bangladeshi Taka"},
       {currecyCode:"BGN",currencyName: "Bulgarian Lev"},
       {currecyCode:"BHD",currencyName: "Bahraini Dinar"},
       {currecyCode: "BIF",currencyName: "Burundian Franc"},
       {currecyCode: "BMD",currencyName: "Bermudan Dollar"},
       {currecyCode:"BND",currencyName: "Brunei Dollar"},
       {currecyCode: "BOB",currencyName: "Bolivian Boliviano"},
       {currecyCode: "BRL",currencyName: "Brazilian Real"},
       {currecyCode: "BSD",currencyName: "Bahamian Dollar"},
       {currecyCode: "BTC",currencyName: "Bitcoin"},
       {currecyCode: "BTN",currencyName: "Bhutanese Ngultrum"},
       {currecyCode:  "BWP",currencyName: "Botswanan Pula"},
       {currecyCode: "BYN",currencyName: "New Belarusian Ruble"},
       {currecyCode: "BYR",currencyName: "Belarusian Ruble"},
       {currecyCode:  "BZD",currencyName: "Belize Dollar"},
       {currecyCode: "CAD",currencyName: "Canadian Dollar"},
       {currecyCode: "CDF",currencyName: "Congolese Franc"},
       {currecyCode: "CHF",currencyName: "Swiss Franc"},
       {currecyCode:  "CLF",currencyName: "Chilean Unit of Account (UF)"},
       {currecyCode:  "CLP",currencyName: "Chilean Peso"},
       {currecyCode:  "CNY",currencyName: "Chinese Yuan"},
       {currecyCode: "COP",currencyName: "Colombian Peso"},
       {currecyCode: "CRC",currencyName: "Costa Rican Colón"},
       {currecyCode: "CUC",currencyName: "Cuban Convertible Peso"},
       {currecyCode: "CUP",currencyName: "Cuban Peso"},
       {currecyCode: "CVE",currencyName: "Cape Verdean Escudo"},
       {currecyCode: "CZK",currencyName: "Czech Republic Koruna"},
       {currecyCode: "DJF",currencyName: "Djiboutian Franc"},
       {currecyCode: "DKK",currencyName: "Danish Krone"},
       {currecyCode: "DOP",currencyName: "Dominican Peso"},
       {currecyCode: "DZD",currencyName: "Algerian Dinar"},
       {currecyCode: "EGP",currencyName: "Egyptian Pound"},
       {currecyCode: "ERN",currencyName: "Eritrean Nakfa"},
       {currecyCode: "ETB",currencyName: "Ethiopian Birr"},
       {currecyCode: "EUR",currencyName: "Euro"},
       {currecyCode: "FJD",currencyName: "Fijian Dollar"},
       {currecyCode: "FKP",currencyName: "Falkland Islands Pound"},
       {currecyCode: "GBP",currencyName: "British Pound Sterling"},
       {currecyCode: "GEL",currencyName: "Georgian Lari"},
       {currecyCode: "GGP",currencyName: "Guernsey Pound"},
       {currecyCode: "GHS",currencyName: "Ghanaian Cedi"},
       {currecyCode: "GIP",currencyName: "Gibraltar Pound"},
       {currecyCode: "GMD",currencyName: "Gambian Dalasi"},
       {currecyCode: "GNF",currencyName: "Guinean Franc"},
       {currecyCode: "GTQ",currencyName: "Guatemalan Quetzal"},
       {currecyCode: "GYD",currencyName: "Guyanaese Dollar"},
       {currecyCode: "HKD",currencyName: "Hong Kong Dollar"},
       {currecyCode: "HNL",currencyName: "Honduran Lempira"},
       {currecyCode: "HRK",currencyName: "Croatian Kuna"},
       {currecyCode: "HTG",currencyName: "Haitian Gourde"},
       {currecyCode: "HUF",currencyName: "Hungarian Forint"},
       {currecyCode: "IDR",currencyName: "Indonesian Rupiah"},
       {currecyCode: "ILS",currencyName: "Israeli New Sheqel"},
       {currecyCode: "IMP",currencyName: "Manx pound"},
       {currecyCode: "INR",currencyName: "Indian Rupee"},
       {currecyCode: "IQD",currencyName: "Iraqi Dinar"},
       {currecyCode: "IRR",currencyName: "Iranian Rial"},
       {currecyCode: "ISK",currencyName: "Icelandic Króna"},
       {currecyCode: "JEP",currencyName: "Jersey Pound"},
       {currecyCode: "JMD",currencyName: "Jamaican Dollar"},
       {currecyCode: "JOD",currencyName: "Jordanian Dinar"},
       {currecyCode: "JPY",currencyName: "Japanese Yen"},
       {currecyCode: "KES",currencyName: "Kenyan Shilling"},
       {currecyCode: "KGS",currencyName: "Kyrgystani Som"},
       {currecyCode: "KHR",currencyName: "Cambodian Riel"},
       {currecyCode: "KMF",currencyName: "Comorian Franc"},
       {currecyCode: "KPW",currencyName: "North Korean Won"},
       {currecyCode: "KRW",currencyName: "South Korean Won"},
       {currecyCode: "KWD",currencyName: "Kuwaiti Dinar"},
       {currecyCode: "KYD",currencyName: "Cayman Islands Dollar"},
       {currecyCode: "KZT",currencyName: "Kazakhstani Tenge"},
       {currecyCode: "LAK",currencyName: "Laotian Kip"},
       {currecyCode: "LBP",currencyName: "Lebanese Pound"},
       {currecyCode: "LKR",currencyName: "Sri Lankan Rupee"},
       {currecyCode: "LRD",currencyName: "Liberian Dollar"},
       {currecyCode: "LSL",currencyName: "Lesotho Loti"},
       {currecyCode: "LTL",currencyName: "Lithuanian Litas"},
       {currecyCode: "LVL",currencyName: "Latvian Lats"},
       {currecyCode: "LYD",currencyName: "Libyan Dinar"},
       {currecyCode: "MAD",currencyName: "Moroccan Dirham"},
       {currecyCode: "MDL",currencyName: "Moldovan Leu"},
       {currecyCode: "MGA",currencyName: "Malagasy Ariary"},
       {currecyCode: "MKD",currencyName: "Macedonian Denar"},
       {currecyCode: "MMK",currencyName: "Myanma Kyat"},
       {currecyCode: "MNT",currencyName: "Mongolian Tugrik"},
       {currecyCode: "MOP",currencyName: "Macanese Pataca"},
       {currecyCode: "MRO",currencyName: "Mauritanian Ouguiya"},
       {currecyCode: "MUR",currencyName: "Mauritian Rupee"},
       {currecyCode: "MVR",currencyName: "Maldivian Rufiyaa"},
       {currecyCode: "MWK",currencyName: "Malawian Kwacha"},
       {currecyCode: "MXN",currencyName: "Mexican Peso"},
       {currecyCode: "MYR",currencyName: "Malaysian Ringgit"},
       {currecyCode: "MZN",currencyName: "Mozambican Metical"},
       {currecyCode: "NAD",currencyName: "Namibian Dollar"},
       {currecyCode: "NGN",currencyName: "Nigerian Naira"},
       {currecyCode: "NIO",currencyName: "Nicaraguan Córdoba"},
       {currecyCode: "NOK",currencyName: "Norwegian Krone"},
       {currecyCode: "NPR",currencyName: "Nepalese Rupee"},
       {currecyCode: "NZD",currencyName: "New Zealand Dollar"},
       {currecyCode: "OMR",currencyName: "Omani Rial"},
       {currecyCode: "PAB",currencyName: "Panamanian Balboa"},
       {currecyCode: "PEN",currencyName: "Peruvian Nuevo Sol"},
       {currecyCode: "PGK",currencyName: "Papua New Guinean Kina"},
       {currecyCode: "PHP",currencyName: "Philippine Peso"},
       {currecyCode: "PKR",currencyName: "Pakistani Rupee"},
       {currecyCode: "PLN",currencyName: "Polish Zloty"},
       {currecyCode: "PYG",currencyName: "Paraguayan Guarani"},
       {currecyCode: "QAR",currencyName: "Qatari Rial"},
       {currecyCode: "RON",currencyName: "Romanian Leu"},
       {currecyCode: "RSD",currencyName: "Serbian Dinar"},
       {currecyCode: "RUB",currencyName: "Russian Ruble"},
       {currecyCode: "RWF",currencyName: "Rwandan Franc"},
       {currecyCode: "SAR",currencyName: "Saudi Riyal"},
       {currecyCode: "SBD",currencyName: "Solomon Islands Dollar"},
       {currecyCode: "SCR",currencyName: "Seychellois Rupee"},
       {currecyCode: "SDG",currencyName: "Sudanese Pound"},
       {currecyCode: "SEK",currencyName: "Swedish Krona"},
       {currecyCode: "SGD",currencyName: "Singapore Dollar"},
       {currecyCode: "SHP",currencyName: "Saint Helena Pound"},
       {currecyCode: "SLL",currencyName: "Sierra Leonean Leone"},
       {currecyCode: "SOS",currencyName: "Somali Shilling"},
       {currecyCode: "SRD",currencyName: "Surinamese Dollar"},
       {currecyCode: "STD",currencyName: "São Tomé and Príncipe Dobra"},
       {currecyCode: "SVC",currencyName: "Salvadoran Colón"},
       {currecyCode: "SYP",currencyName: "Syrian Pound"},
       {currecyCode: "SZL",currencyName: "Swazi Lilangeni"},
       {currecyCode: "THB",currencyName: "Thai Baht"},
       {currecyCode: "TJS",currencyName: "Tajikistani Somoni"},
       {currecyCode: "TMT",currencyName: "Turkmenistani Manat"},
       {currecyCode: "TND",currencyName: "Tunisian Dinar"},
       {currecyCode: "TOP",currencyName: "Tongan Paʻanga"},
       {currecyCode: "TRY",currencyName: "Turkish Lira"},
       {currecyCode: "TTD",currencyName: "Trinidad and Tobago Dollar"},
       {currecyCode: "TWD",currencyName: "New Taiwan Dollar"},
       {currecyCode: "TZS",currencyName: "Tanzanian Shilling"},
       {currecyCode: "UAH",currencyName: "Ukrainian Hryvnia"},
       {currecyCode: "UGX",currencyName: "Ugandan Shilling"},
       {currecyCode: "USD",currencyName: "United States Dollar"},
       {currecyCode: "UYU",currencyName: "Uruguayan Peso"},
       {currecyCode: "UZS",currencyName: "Uzbekistan Som"},
       {currecyCode: "VEF",currencyName: "Venezuelan Bolívar Fuerte"},
       {currecyCode: "VND",currencyName: "Vietnamese Dong"},
       {currecyCode: "VUV",currencyName: "Vanuatu Vatu"},
       {currecyCode: "WST",currencyName: "Samoan Tala"},
       {currecyCode: "XAF",currencyName: "CFA Franc BEAC"},
       {currecyCode: "XAG",currencyName: "Silver (troy ounce)"},
       {currecyCode: "XAU",currencyName: "Gold (troy ounce)"},
       {currecyCode: "XCD",currencyName: "East Caribbean Dollar"},
       {currecyCode: "XDR",currencyName: "Special Drawing Rights"},
       {currecyCode: "XOF",currencyName: "CFA Franc BCEAO"},
       {currecyCode: "XPF",currencyName: "CFP Franc"},
       {currecyCode: "YER",currencyName: "Yemeni Rial"},
       {currecyCode: "ZAR",currencyName: "South African Rand"},
       {currecyCode: "ZMK",currencyName: "Zambian Kwacha (pre-2013)"},
       {currecyCode: "ZMW",currencyName: "Zambian Kwacha"},
       {currecyCode: "ZWL",currencyName: "Zimbabwean Dollar"}
   ]